[build]
  publish = "."
  command = "echo 'No build required'"

[[headers]]
  for = "/video/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "video/mp4"
    Access-Control-Allow-Origin = "*"
    Accept-Ranges = "bytes"

[build.processing]
  skip_processing = true

[build.processing.videos]
  compress = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/docs/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 