[build]
  publish = "."
  command = ""

[[headers]]
  for = "/video/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "video/mp4"
    Accept-Ranges = "bytes"

[[headers]]
  for = "/docs/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """
      default-src 'self' https://cdn.jsdelivr.net;
      img-src 'self' data: https:;
      style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net;
      script-src 'self' https://cdn.jsdelivr.net;
      connect-src 'self';
      font-src 'self';
      object-src 'none';
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
    """

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "video/mp4"
    Accept-Ranges = "bytes"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 