[build]
  publish = "."

[[headers]]
  for = "/video/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/docs/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 